# Configuration file for Sniper Swing Bot

# Telegram Configuration
telegram:
  token: ${TELEGRAM_BOT_TOKEN}
  chat_id: ${TELEGRAM_ID}
  enabled: true
  command_server: true

# Trading Configuration
trading:
  capital: ${CAPITAL:170000}
  max_daily_trades: 3
  max_simultaneous_trades: 3
  risk_per_trade: 0.33

# Market Configuration
market:
  timezone: "Asia/Kolkata"
  trading_hours:
    start: "09:15"
    end: "15:30"
    friday_early_close: "15:15"

# Symbols to trade
symbols:
  - NIFTY
  - BANKNIFTY  
  - SENSEX
  - FINNIFTY

# Logging Configuration
logging:
  level: INFO
  file: "sniper_swing.log"
  max_size: 10485760  # 10MB
  backup_count: 3

# Health Monitoring
health_monitor:
  enabled: true
  interval: 60  # seconds
  alerts:
    cpu_threshold: 80
    memory_threshold: 85
    disk_threshold: 90

# AI Configuration
ai:
  enabled: true
  learning_enabled: true
  analysis_enabled: true

# Signal Analysis
signal_analysis:
  minimum_strength: 7.0
  confidence_threshold: "MEDIUM"
  components:
    trend_alignment: 0.25
    momentum_strength: 0.20
    volume_confirmation: 0.15
    support_resistance: 0.15
    rsi_position: 0.10
    moving_average_confluence: 0.10
    volatility_factor: 0.05
